// constants.ts
import type { LearningRecord, GradeRecord, GradeStats } from './types';

export const mockRecords: LearningRecord[] = [
    // ===== 状态1: 待提交 (pending) - 需要上传作业图片和课堂评语 =====
    {
      id: 'r1',
      title: '导数的几何意义 · 课后练习',
      subject: '数学',
      className: '高二(3)班',
      lessonPlanId: 'lp-001',
      lessonPlanTitle: '导数的几何意义',
      status: 'pending',
      createdAt: '2026-09-03 14:30',
      timeSpent: 35,
      images: [],
    },
    {
      id: 'r2',
      title: '二次函数单元教案',
      subject: '数学',
      className: '高二(1)班',
      lessonPlanId: 'lp-002',
      lessonPlanTitle: '二次函数单元',
      status: 'pending',
      createdAt: '2026-09-02 10:20',
      timeSpent: 28,
      images: [],
    },
  
    // ===== 状态2: 待审核 (submitted) - 需要教师批改 =====
    {
      id: 'r3',
      title: '英语阅读理解专项训练',
      subject: '英语',
      className: '高二(3)班',
      lessonPlanId: 'lp-003',
      lessonPlanTitle: '英语阅读理解',
      status: 'submitted',
      createdAt: '2026-09-01 16:30',
      submittedAt: '2026-09-02 09:00',
      timeSpent: 42,
      images: ['img1', 'img2'],
      classEvaluation: {
        rating: 4,
        comment: '课堂表现积极，阅读理解能力有提升。',
        teacher: '张老师',
        createdAt: '2026-09-02 09:00',
        type: '课堂记录',
      },
    },
    {
      id: 'r4',
      title: '三角函数单元测验',
      subject: '数学',
      className: '高二(1)班',
      lessonPlanId: 'lp-004',
      lessonPlanTitle: '三角函数',
      status: 'submitted',
      createdAt: '2026-08-31 14:00',
      submittedAt: '2026-09-01 10:30',
      timeSpent: 38,
      images: ['img1', 'img2', 'img3'],
      classEvaluation: {
        rating: 3.5,
        comment: '课堂参与度良好，但计算需加强。',
        teacher: '李老师',
        createdAt: '2026-09-01 10:30',
        type: '课堂记录',
      },
    },
  
    // ===== 状态3: 已完成 (graded) - 可查看详情 =====
    {
      id: 'r5',
      title: '期中考试 · 数学',
      subject: '数学',
      className: '高二(3)班',
      lessonPlanId: 'lp-005',
      lessonPlanTitle: '期中考试',
      status: 'graded',
      createdAt: '2026-08-20 10:00',
      submittedAt: '2026-08-21 08:30',
      gradedAt: '2026-08-22 16:00',
      score: 85,
      totalScore: 100,
      masteryRate: 78,
      timeSpent: 60,
      images: ['img1', 'img2', 'img3', 'img4'],
      teacherFeedback: '基础知识扎实，解题思路清晰。建议在压轴题上多下功夫。',
      classEvaluation: {
        rating: 4.5,
        comment: '课堂表现优秀，积极参与讨论，作业完成质量高。',
        teacher: '张老师',
        createdAt: '2026-08-20 10:30',
        type: '课堂记录',
      },
      aiResult: {
        score: 85,
        totalScore: 100,
        level: '良好',
        basicScore: 55,
        basicTotal: 60,
        basicAccuracy: 92,
        advancedScore: 30,
        advancedTotal: 40,
        advancedAccuracy: 75,
        errors: [
          { question: '第8题', reason: '综合应用能力需加强' },
          { question: '第10题', reason: '计算粗心' },
        ],
      },
    },
    {
      id: 'r6',
      title: '导数单元测验',
      subject: '数学',
      className: '高二(3)班',
      lessonPlanId: 'lp-006',
      lessonPlanTitle: '导数单元',
      status: 'graded',
      createdAt: '2026-08-15 14:00',
      submittedAt: '2026-08-16 09:00',
      gradedAt: '2026-08-17 15:30',
      score: 68,
      totalScore: 100,
      masteryRate: 62,
      timeSpent: 45,
      images: ['img1'],
      teacherFeedback: '基础概念需要巩固，建议加强练习。',
      classEvaluation: {
        rating: 3,
        comment: '课堂注意力需要加强，偶尔走神。',
        teacher: '张老师',
        createdAt: '2026-08-15 14:30',
        type: '课堂记录',
      },
      aiResult: {
        score: 68,
        totalScore: 100,
        level: '中等',
        basicScore: 40,
        basicTotal: 60,
        basicAccuracy: 67,
        advancedScore: 28,
        advancedTotal: 40,
        advancedAccuracy: 70,
        errors: [
          { question: '第2题', reason: '极限概念理解不清晰' },
          { question: '第5题', reason: '切线方程应用不熟练' },
          { question: '第9题', reason: '公式记忆混淆' },
        ],
      },
    },
];

export const mockGrades: GradeRecord[] = [
  {
    id: 'g1',
    name: '函数单元测验',
    subject: '数学',
    score: 92,
    totalScore: 100,
    date: '2026-09-03',
    images: ['img1', 'img2'],
    createdAt: '2026-09-03 10:00',
  },
  {
    id: 'g2',
    name: '期中考试',
    subject: '数学',
    score: 85,
    totalScore: 100,
    date: '2026-08-20',
    images: ['img1', 'img2', 'img3'],
    createdAt: '2026-08-20 14:00',
  },
  {
    id: 'g3',
    name: '导数单元测验',
    subject: '数学',
    score: 68,
    totalScore: 100,
    date: '2026-08-15',
    images: ['img1'],
    createdAt: '2026-08-15 11:00',
  },
];

export const mockGradeStats: GradeStats = {
  total: 6,
  average: 82.5,
  improvement: 5,
  uploadedImages: 3,
};